{
    "body": None,
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
        "Host": "127.0.0.1:3000",
        "Postman-Token": "3f16aab0-83ab-445a-bd32-a86a1da88cfe",
        "User-Agent": "PostmanRuntime/7.32.3",
        "X-Forwarded-Port": "3000",
        "X-Forwarded-Proto": "http",
    },
    "httpMethod": "GET",
    "isBase64Encoded": False,
    "multiValueHeaders": {
        "Accept": ["*/*"],
        "Accept-Encoding": ["gzip, deflate, br"],
        "Connection": ["keep-alive"],
        "Host": ["127.0.0.1:3000"],
        "Postman-Token": ["3f16aab0-83ab-445a-bd32-a86a1da88cfe"],
        "User-Agent": ["PostmanRuntime/7.32.3"],
        "X-Forwarded-Port": ["3000"],
        "X-Forwarded-Proto": ["http"],
    },
    "multiValueQueryStringParameters": None,
    "path": "/schedule/1",
    "pathParameters": {"schedule_id": "1"},
    "queryStringParameters": None,
    "requestContext": {
        "accountId": "123456789012",
        "apiId": "1234567890",
        "domainName": "127.0.0.1:3000",
        "extendedRequestId": None,
        "httpMethod": "GET",
        "identity": {
            "accountId": None,
            "apiKey": None,
            "caller": None,
            "cognitoAuthenticationProvider": None,
            "cognitoAuthenticationType": None,
            "cognitoIdentityPoolId": None,
            "sourceIp": "127.0.0.1",
            "user": None,
            "userAgent": "Custom User Agent String",
            "userArn": None,
        },
        "path": "/schedule/{schedule_id}",
        "protocol": "HTTP/1.1",
        "requestId": "7014c241-6ef3-4ad6-abcf-4df56370d452",
        "requestTime": "27/Sep/2023:05:35:23 +0000",
        "requestTimeEpoch": 1695792923,
        "resourceId": "123456",
        "resourcePath": "/schedule/{schedule_id}",
        "stage": "staging",
    },
    "resource": "/schedule/{schedule_id}",
    "stageVariables": None,
    "version": "1.0",
}
